CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('customer','admin','superadmin') DEFAULT 'customer',status ENUM('active','blocked') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(140) NOT NULL UNIQUE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS products(id INT AUTO_INCREMENT PRIMARY KEY,category_id INT NULL,name VARCHAR(180) NOT NULL,slug VARCHAR(200) NOT NULL UNIQUE,sku VARCHAR(80) NOT NULL UNIQUE,description TEXT,price BIGINT NOT NULL,stock INT NOT NULL DEFAULT 0,image VARCHAR(500),active TINYINT(1) DEFAULT 1,sales INT DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,receiver VARCHAR(120) NOT NULL,phone VARCHAR(40),address TEXT NOT NULL,subtotal BIGINT NOT NULL,discount BIGINT NOT NULL DEFAULT 0,shipping BIGINT NOT NULL DEFAULT 0,total BIGINT NOT NULL,payment_method ENUM('cod','online') DEFAULT 'cod',status ENUM('pending','paid','processing','shipped','completed','cancelled') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_items(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,product_id INT NULL,product_name VARCHAR(180) NOT NULL,price BIGINT NOT NULL,qty INT NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS coupons(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(80) NOT NULL UNIQUE,type ENUM('percent','fixed') DEFAULT 'percent',value BIGINT NOT NULL,min_amount BIGINT NOT NULL DEFAULT 0,usage_limit INT NULL,used_count INT NOT NULL DEFAULT 0,expires_at DATETIME NULL,active TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings(`key` VARCHAR(100) PRIMARY KEY,value TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO settings(`key`,value) VALUES('shipping_cost','0');
INSERT IGNORE INTO categories(name,slug) VALUES('دیجیتال','digital'),('پوشاک','fashion'),('گیمینگ','gaming'),('لوازم جانبی','accessories');
INSERT IGNORE INTO products(category_id,name,slug,sku,description,price,stock,image,active,sales) VALUES
(3,'هدست گیمینگ RGB','gaming-headset','GM-001','هدست حرفه‌ای با میکروفون و نورپردازی.',1490000,25,'https://placehold.co/600x600?text=Headset',1,120),
(4,'کیبورد مکانیکی','mechanical-keyboard','GM-002','کیبورد مکانیکی مناسب بازی و برنامه‌نویسی.',2190000,18,'https://placehold.co/600x600?text=Keyboard',1,86),
(2,'هودی مشکی','black-hoodie','FA-001','هودی ساده و راحت.',890000,40,'https://placehold.co/600x600?text=Hoodie',1,70),
(1,'ماوس بی‌سیم','wireless-mouse','AC-001','ماوس بی‌سیم کم‌مصرف.',590000,55,'https://placehold.co/600x600?text=Mouse',1,150);
INSERT IGNORE INTO coupons(code,type,value,min_amount,usage_limit,active) VALUES('WELCOME10','percent',10,0,100,1);
